### ISSUE TITLE
Training with raccoon dataset - Uninitialized value yolo/convolutional_52/batch_norm/beta

### ISSUE THREAD

**Issue by AGrosserHH** [viplix3/YOLO#5]
Hi, I am trying to train the dataset with the raccoon dataset. However I get an error of 
019-05-22 21:37:21.806998: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at iterator_ops.cc:947 : Cancelled:                                                     | 0/12 [00:00<?, ?it/s]
2019-05-22 21:37:21.811518: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at iterator_ops.cc:947 : Cancelled: 
Traceback (most recent call last):
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value yolo/convolutional_52/batch_norm/beta
	 [[{{node yolo/convolutional_52/batch_norm/beta/read}} = Identity[T=DT_FLOAT, _class=["loc:@yolo/...1/Switch_2"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](yolo/convolutional_52/batch_norm/beta)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 249, in main
    train(config.model_dir, config.logs_dir, config.classes_path)
  File "train.py", line 199, in train
    grads], feed_dict={is_training: True, mode: 1})
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value yolo/convolutional_52/batch_norm/beta
	 [[node yolo/convolutional_52/batch_norm/beta/read (defined at /home/andi/GitClone/YOLO1/build_model.py:165)  = Identity[T=DT_FLOAT, _class=["loc:@yolo/...1/Switch_2"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](yolo/convolutional_52/batch_norm/beta)]]

Caused by op 'yolo/convolutional_52/batch_norm/beta/read', defined at:
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 249, in main
    train(config.model_dir, config.logs_dir, config.classes_path)
  File "train.py", line 104, in train
    output = yolo(images, is_training, config.yolov3_cfg_path, config.num_classes)
  File "/home/andi/GitClone/YOLO1/build_model.py", line 165, in yolo
    bn_layer = tf.layers.batch_normalization(inputs=conv_layer, momentum=momentum, epsilon=1e-3, center=True, scale=True, training=is_training, name=scope+section+'/batch_norm')
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/layers/normalization.py", line 309, in batch_normalization
    return layer.apply(inputs, training=training)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 817, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/keras/layers/normalization.py", line 297, in build
    trainable=True)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 288, in add_weight
    getter=vs.get_variable)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 609, in add_weight
    aggregation=aggregation)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/training/checkpointable/base.py", line 639, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 922, in _get_single_variable
    aggregation=aggregation)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 1329, in __init__
    constraint=constraint)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 1491, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3454, in identity
    "Identity", input=input, name=name)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/andi/anaconda3/envs/cpu1/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value yolo/convolutional_52/batch_norm/beta
	 [[node yolo/convolutional_52/batch_norm/beta/read (defined at /home/andi/GitClone/YOLO1/build_model.py:165)  = Identity[T=DT_FLOAT, _class=["loc:@yolo/...1/Switch_2"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](yolo/convolutional_52/batch_norm/beta)]]

Could you please help me?

**Comment by viplix3** [comment]
Sorry, I've been away for a while.
Will check and get back to you ASAP.

**Comment by viplix3** [comment]
Hello, I couldn't reproduce the error you mentioned.
Maybe it was a bug in the previous release. Can you please try training the model using the latest commit?
